!function(e){"use strict"
function n(e,n,t){var o=document.createElement(e)
return n&&o.setAttribute("class",n),t&&(o.innerText=t),o}function t(){var e=document.createElement("style")
e.innerHTML='            \n.mqq-debug-panel{            \n    position: fixed;            \n    top: 0;            \n    left: 0;            \n    right: 0;            \n    font-size: 10px;            \n    background-color: rgba(0,0,0,.7);            \n    color: #fff;            \n    z-index: 100000;            \n}            \n.mqq-debug-scroller{            \n    height: 150px;            \n    overflow: auto;            \n    padding: 5px 10px 15px;            \n    line-height: 16px;            \n    -webkit-overflow-scrolling: touch;            \n}            \n.mqq-debug-dragbar{            \n    position: absolute;            \n    margin: 0;            \n    height: 20px;            \n    width: 50px;            \n    background-color: rgba(18, 98, 168,.4);            \n    border-radius: 2px 2px 0 0;            \n    right: 10px;            \n    bottom: 0;            \n}            \n.mqq-debug-dragbar:after{            \n    position: absolute;            \n    left: 50%;            \n    top: 50%;            \n    content: "";            \n    border: #fff solid;            \n    border-width: 1px 0;            \n    width: 25px;            \n    height: 5px;            \n    margin: -3px 0 0 -13px;            \n}            \n.mqq-debug-clear,            \n.mqq-debug-watch{            \n    display: block;            \n    font-size: 9px;            \n    text-align: center;            \n    background-color: #eee;            \n    color: #333;            \n    margin: 0;            \n    position: absolute;            \n    bottom: 5px;            \n    left: 5px;            \n    height: 15px;            \n    width: 40px;            \n    line-height: 15px;            \n    border-radius: 10px;            \n    box-shadow: 0 0 3px rgba(0,0,0,.5)            \n}            \n.mqq-debug-watch{            \n    left: 50px;            \n    width: auto;            \n    padding: 0 8px;            \n}',document.getElementsByTagName("head")[0].appendChild(e)
var t=n("div","mqq-debug-panel"),i=n("div","mqq-debug-scroller"),r=n("p","mqq-debug-dragbar"),a=n("p","mqq-debug-clear","清除"),d=n("p","mqq-debug-watch","筛选")
t.appendChild(i),t.appendChild(r),t.appendChild(a),t.appendChild(d),(document.body||document.documentElement).appendChild(t)
var l,c
return r.addEventListener("touchstart",function(e){e.preventDefault(),l=e.touches[0].pageY,c=i.clientHeight},!1),r.addEventListener("touchmove",function(e){e.preventDefault()
var n=e.touches[0].pageY
i.style.height=c+(n-l)+"px"},!1),a.addEventListener("touchstart",function(){o.clear()},!1),d.addEventListener("touchstart",function(){if(this.classList.contains("mqq-debug-watching"))o.watch(),this.innerText="筛选",this.classList.remove("mqq-debug-watching")
else{var e=prompt("输入您要关注的接口，例如：setTitle")
o.watch(e)?(this.innerText=e,this.classList.add("mqq-debug-watching")):alert("您输入的接口格式不正确")}},!1),{logPanel:t,scroller:i,drapBar:r,clear:a}}if(!e.Nativefirebug){var o=e.Nativefirebug=function(){var e,n=t(),o=""
return{log:function(t){var i=""
if(e&&t.method===e.method||!e)for(var r in t){var a=t[r]
"object"==typeof a&&(a=JSON.stringify(a)),i+="warn"===r?'<p style="color:#fd7f00">'+r+": "+decodeURIComponent(a)+"</p>":"error"===r?'<p style="color:#fe432c">'+r+": "+decodeURIComponent(a)+"</p>":"url"===r?'<p style="color:#80d741">'+r+": "+decodeURIComponent(a)+"</p>":r+": "+decodeURIComponent(a)+"<br>"}i&&(o+=i+"-------------------------<br>",n.scroller.innerHTML=o,setTimeout(function(){n.scroller.scrollTop=n.scroller.scrollHeight},0))},watch:function(n){return n?(e={method:n},!0):(e=null,!1)},unwatch:function(){watchNs="",watchMethod=""},clear:function(){n.scroller.innerHTML=o=""}}}(),i=/(iPad|iPhone|iPod).*? (IPad)?QQ\/([\d\.]+)/,r=/\bV1_AND_SQI?_([\d\.]+)(.*? QQ\/([\d\.]+))?/,a=navigator.userAgent
i.test(a)||r.test(a)||(o.ua="Mozilla/5.0 (iPhone; CPU iPhone OS 7_1_2 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Mobile/11D257 QQ/5.3.2.424 NetType/WIFI Mem/46"),e.NativeApi&&(e.NativeApi.debuging=!0)}}(this)
